Repository pigMercury/grace-shopper, pull requests merged in 2019-01, with the labels that each got.

#4 Create Social_Contract.md
  Social_Contract.md
Labels: in progress

#23 travis: activate deployment
  .travis.yml
Labels: in progress

#26 made user model
  server/api/destinations.js
  server/api/destinations.spec.js
  server/api/index.js
  server/db/models/index.js
  server/db/models/user.js
Labels: in progress

#27 added destination order and paymentInfo models
  server/api/destination.js
  server/api/destination.spec.js
  server/api/destinations.spec.js
  server/db/models/destination.js
  server/db/models/index.js
  server/db/models/order.js
  server/db/models/paymentInfo.js
  server/db/models/user.spec.js
Labels: git-generated, in progress

#28 Created HomePage component which displays when url matches '/home'
  client/components/home-page.js
  client/components/index.js
  client/routes.js
  public/style.css
Labels: git-generated

#31 Typo
  server/api/index.js
  server/db/models/index.js
Labels: in progress

#34 Seed #20
  script/seed.js
Labels: Waiting for Review, git-generated, mvp, sequelize

#37 modified user route
  server/api/order.spec.js
  server/api/user.js
Labels: in progress

#43 41 order tests
  client/components/allDestinations.js
  client/components/oneDestination.js
  client/routes.js
  client/store/destination.js
  client/store/index.js
  public/style.css
  server/api/destination.spec.js
  server/api/order.spec.js
  server/api/user.spec.js
  server/db/models/destination.js
Labels: in progress

#44 resolve 41-order-tests
  client/components/allDestinations.js
  client/components/index.js
  client/components/oneDestination.js
  client/routes.js
  client/store/index.js
  script/seed.js
Labels: Waiting for Review, git-generated, mvp, react

#45 11 orders sub reducer
  client/store/destination.js
  client/store/index.js
  client/store/order.js
  client/store/trip.js
Labels: in progress

#47 46 cart routes
  client/store/order.js
  server/api/index.js
  server/api/order.js
  server/api/trip.js
  server/db/models/trip.js
Labels: in progress

#46 13 cart component
  client/components/allDestinations.js
  client/components/cart.js
  client/components/destinationPage.js
  client/components/index.js
  client/components/oneDestination.js
  client/routes.js
  client/store/order.js
  client/store/trip.js
  server/api/destination.spec.js
  server/api/order.spec.js
  server/api/user.spec.js
Labels: in progress

#50 started cart component
  client/app.js
  client/components/allDestinations.js
  client/components/cart.js
  client/components/destinationPage.js
  client/components/index.js
  client/components/navbar.js
  client/components/oneDestination.js
  client/routes.js
  client/store/trip.js
  public/favicon.ico
  public/index.html
  server/api/trip.js
Labels: in progress

#60 fix switch logic so destinations still viewable for logged in user
  client/routes.js
Labels: in progress

#62 can add stuff to cart
  client/components/allDestinations.js
  client/components/cart.js
  client/components/oneDestination.js
  client/store/trip.js
  server/api/trip.js
Labels: in progress

#63 57 securing routes
  client/components/authForm.js
  client/components/homePage.js
  client/components/index.js
  client/components/userHome.js
  client/components/userHome.spec.js
  server/api/order.js
  server/api/trip.js
  server/api/user.js
  server/api/user.spec.js
Labels: Waiting for Review

#64 resolves #51 added onclick addToCart for destinationPage
  client/components/cart.js
  client/components/destinationPage.js
  client/components/oneDestination.js
Labels: in progress

#66 niced up home page and navbar
  client/components/homePage.js
  client/components/navbar.js
  client/components/userHome.js
  client/components/userHome.spec.js
  public/style.css
  server/api/order.spec.js
  server/api/user.spec.js
Labels: in progress

#67 resolves #40 stripe payment functionality added
  client/components/cart.js
  client/components/checkout.js
  server/api/index.js
  server/api/payment.js
Labels: in progress

#69 resolves #68 fixed amount in charge function
  server/api/payment.js
Labels: in progress

#83 resolves #82 fixed complete order flow
  client/components/cart.js
  client/components/checkout.js
  client/store/order.js
  server/api/order.js
Labels: in progress

#72 fixed last model test and cart cost total cost display
  client/components/cart.js
  package-lock.json
  package.json
  server/db/models/trip.spec.js
Labels: in progress

#88 cart clears upon checkout
  client/components/cart.js
  client/components/checkout.js
  client/store/trip.js
Labels: in progress

#90 resolves #89 create order now attaches user id
  client/store/order.js
  server/api/order.js
Labels: in progress

#93 resolves #92 fixed double trip bug
  client/store/trip.js
Labels: in progress

#91 79 can update item quantity
  client/components/cart.js
  client/components/cartItem.js
  server/api/trip.js
Labels: in progress

#94 can delete items from cart
  client/components/cartItem.js
  client/store/order.js
  client/store/trip.js
  server/api/trip.js
Labels: in progress

#96 prettier alerts working for all accept payment success or failed message
  client/app.js
  client/components/cartItem.js
  client/components/destinationPage.js
  client/components/oneDestination.js
  client/index.js
  package-lock.json
  package.json
Labels: in progress

#98 resolves#75 destination page styling
  client/components/carousel.js
  client/components/destinationPage.js
  package-lock.json
  package.json
  public/index.html
  public/style.css
  script/seed.js
  server/db/models/destination.js
Labels: in progress

#97 resolves #78 - added order history functionality
  client/components/index.js
  client/components/navbar.js
  client/components/orderHistory.js
  client/routes.js
  public/index.html
  public/style.css
Labels: in progress

#99 created a border and margin for each destination rendered in list
  public/style.css
Labels: in progress

#103 Prev next buttons for destination page
  client/components/destinationPage.js
  client/store/destination.js
Labels: in progress

#104 resolve #73 by trying to sidestep bootstrap on the components we don't want it on
  client/components/navbar.js
  client/components/oneDestination.js
  client/components/orderHistory.js
  public/bootstrap-alt.css
  public/index.html
  public/style.css
  script/seed.js
Labels: in progress

#105 deleted imageURL from destructured props
  client/components/destinationPage.js
Labels: in progress

#106 resolve #106 Styling from home
  client/components/cart.js
  client/components/cartItem.js
  client/components/destinationPage.js
  client/components/homePage.js
  client/components/orderHistory.js
  public/bootstrap-alt.css
  public/index.html
  public/style.css
Labels: finishing-touches, in progress

#108 resolves #84 removed debugging console logs
  client/components/carousel.js
  client/components/destinationPage.js
  client/components/orderHistory.js
  client/index.js
  client/store/order.js
  client/store/trip.js
  server/api/order.js
  server/api/payment.js
  server/api/trip.js
Labels: in progress

#109 removed google line
  client/components/authForm.js
Labels: finishing-touches, in progress
